<a href="https://colab.research.google.com/github/fneilson/stereotypes/blob/master/2.A3_1_upload_raw_data_Fiona_Neilson.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [ ]:
import pandas as pd

# Upload YouTube comments files

## 1. This dataframe contains #Hazara files

In [ ]:
# read all YouTube comments datasets & save as pandas dataframes
# 7 files
import pandas as pd
import glob
import os

path = '/content/drive/MyDrive/MC/Assessments/A2 & A3/scraped_data/H' 
all_files = glob.glob(os.path.join(path, "*.xlsx"))

df = pd.concat((pd.read_excel(f) for f in all_files), ignore_index=True)

In [ ]:
df.head()

                                             comment
0                                                NaN
1                                                NaN
2  Another amazing video! So wonderful to see all...
3  Beautiful people, love from Iran to my lovely ...
4                             Love my nation Hazara

In [ ]:
len(df)

526

In [ ]:
# drop NaNs
df = df.dropna()
df

                                               comment
2    Another amazing video! So wonderful to see all...
3    Beautiful people, love from Iran to my lovely ...
4                               Love my nation Hazara
5                                   سلامت باشید دوستان
6                                    درودها قومای عزیز
..                                                 ...
521  Hazara people lived in Afghanistan for 2500 ye...
522  I am a Mongol. Hazaras are not descendants' of...
523                 Hazara Turko Mongol people\n
524                   Hazaras were massacared.\n
525          Can’t you have a better presenter\n

[519 rows x 1 columns]

In [ ]:
len(df)

519

In [ ]:
# add columns to show hashtag and source
# add a constant 

df=df.assign(hashtag='Hazara', source="YouTube")
df.head()

                                             comment hashtag   source
2  Another amazing video! So wonderful to see all...  Hazara  YouTube
3  Beautiful people, love from Iran to my lovely ...  Hazara  YouTube
4                             Love my nation Hazara   Hazara  YouTube
5                                 سلامت باشید دوستان  Hazara  YouTube
6                                  درودها قومای عزیز  Hazara  YouTube

## 2. This dataframe contains #StopHazaraGenocide files

In [ ]:
# read all YouTube comments datasets & save as pandas dataframes
# 21 files
import pandas as pd
import glob
import os

path = '/content/drive/MyDrive/MC/Assessments/A2 & A3/scraped_data/SHG' 
all_files = glob.glob(os.path.join(path, "*.xlsx"))

df2 = pd.concat((pd.read_excel(f) for f in all_files), ignore_index=True)

In [ ]:
df2.head()

                                             comment
0                                #StopHazaraGenocide
1                                 StopHazaraGenocide
2                              Thank you for sharing
3        #StopHazaraGenocide #stop #Hazara #Genocide
4  7 oct 2022 ham tazahorat sartasari dar 91 kish...

In [ ]:
len(df2)

2470

In [ ]:
# drop NaNs
df2 = df2.dropna()
df2

                                                comment
0                                   #StopHazaraGenocide
1                                    StopHazaraGenocide
2                                 Thank you for sharing
3           #StopHazaraGenocide #stop #Hazara #Genocide
4     7 oct 2022 ham tazahorat sartasari dar 91 kish...
...                                                 ...
2461  بیرق هزارستان را چرا بلند کردید وقتیکه خود افغ...
2462  Dear Sarwari saib. You are Pakistani Hazara. S...
2465  Protest in Melbourne Australia Against Hazara ...
2466  On the 9th of September, a rally of protestant...
2469  You're signed out of YouTube\nSign in to like ...

[2403 rows x 1 columns]

In [ ]:
len(df2)

2403

In [ ]:
# add columns to show hashtag and source (i.e. add a constant) 
df2=df2.assign(hashtag='SHG', source="YouTube")
df2.head()

                                             comment hashtag   source
0                                #StopHazaraGenocide     SHG  YouTube
1                                 StopHazaraGenocide     SHG  YouTube
2                              Thank you for sharing     SHG  YouTube
3        #StopHazaraGenocide #stop #Hazara #Genocide     SHG  YouTube
4  7 oct 2022 ham tazahorat sartasari dar 91 kish...     SHG  YouTube

# Merge dataframes

In [ ]:
# join #Hazara and #StopHazaraGenocide
# concatenate
frames = [df, df2]
yt = pd.concat(frames).reset_index(drop=True)

In [ ]:
len(yt)

2922

In [ ]:
yt

                                                comment hashtag   source
0     Another amazing video! So wonderful to see all...  Hazara  YouTube
1     Beautiful people, love from Iran to my lovely ...  Hazara  YouTube
2                                Love my nation Hazara   Hazara  YouTube
3                                    سلامت باشید دوستان  Hazara  YouTube
4                                     درودها قومای عزیز  Hazara  YouTube
...                                                 ...     ...      ...
2917  بیرق هزارستان را چرا بلند کردید وقتیکه خود افغ...     SHG  YouTube
2918  Dear Sarwari saib. You are Pakistani Hazara. S...     SHG  YouTube
2919  Protest in Melbourne Australia Against Hazara ...     SHG  YouTube
2920  On the 9th of September, a rally of protestant...     SHG  YouTube
2921  You're signed out of YouTube\nSign in to like ...     SHG  YouTube

[2922 rows x 3 columns]

In [ ]:
yt = yt.drop([2919, 2920, 2921])
yt

                                                comment hashtag   source
0     Another amazing video! So wonderful to see all...  Hazara  YouTube
1     Beautiful people, love from Iran to my lovely ...  Hazara  YouTube
2                                Love my nation Hazara   Hazara  YouTube
3                                    سلامت باشید دوستان  Hazara  YouTube
4                                     درودها قومای عزیز  Hazara  YouTube
...                                                 ...     ...      ...
2914       stop hazara genocide in Afghanistan \n           SHG  YouTube
2915  #stophazaragenocide\n#StopPanjshirigenocide\n#...     SHG  YouTube
2916            Lanat shuna da dushmanan hazara\n           SHG  YouTube
2917  بیرق هزارستان را چرا بلند کردید وقتیکه خود افغ...     SHG  YouTube
2918  Dear Sarwari saib. You are Pakistani Hazara. S...     SHG  YouTube

[2919 rows x 3 columns]

# Detect languages

In [ ]:
!pip install langdetect

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
Collecting langdetect
  Downloading langdetect-1.0.9.tar.gz (981 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 981.5/981.5 kB 15.8 MB/s eta 0:00:00
  Preparing metadata (setup.py) ... done
Requirement already satisfied: six in /usr/local/lib/python3.9/dist-packages (from langdetect) (1.16.0)
Building wheels for collected packages: langdetect
  Building wheel for langdetect (setup.py) ... done
  Created wheel for langdetect: filename=langdetect-1.0.9-py3-none-any.whl size=993243 sha256=2353d14c9920fd842090b303fecd1abb3746e7751bed7fdd900007e9c2a0938b
  Stored in directory: /root/.cache/pip/wheels/d1/c1/d9/7e068de779d863bc8f8fc9467d85e25cfe47fa5051fff1a1bb
Successfully built langdetect
Installing collected packages: langdetect
Successfully installed langdetect-1.0.9

In [ ]:
from langdetect import detect

**IMPORTANT** DO NOT RE-RUN THIS FUNCTION AS IT WILL CHANGE THE ENCODINGS

In [ ]:
# create a function to detect language and add to the dataframe
def det(x):
    try:
        lang = detect(x)
    except:
        lang = 'Other'
    return lang

yt['lang'] = yt['comment'].apply(det)

In [ ]:
# download yt as v2
# IMPORTANT - do not re-run the language detection as it will change the encodings
yt.to_excel("/content/drive/MyDrive/MC/Assessments/A2 & A3/scraped_data/yt_langs_detected2.xlsx", header=True, index=True)

In [ ]:
len(yt)

2919

### Review non-English comments

For language codes: https://en.wikipedia.org/wiki/List_of_ISO_639-1_codes

In [ ]:
yt = pd.read_excel('/content/drive/MyDrive/MC/Assessments/A2 & A3/scraped_data/yt_langs_detected.xlsx')

In [ ]:
yt.head()

                                             comment hashtag   source lang
0  Another amazing video! So wonderful to see all...  Hazara  YouTube   en
1  Beautiful people, love from Iran to my lovely ...  Hazara  YouTube   en
2                             Love my nation Hazara   Hazara  YouTube   en
3                                 سلامت باشید دوستان  Hazara  YouTube   fa
4                                  درودها قومای عزیز  Hazara  YouTube   fa

In [ ]:
# get all rows where lang != en
is_not_eng = yt['lang'] != 'en'
df_not_eng = yt[is_not_eng]
len(df_not_eng)

807

In [ ]:
# count levels of lang
df_not_eng['lang'].value_counts()

es       122
id        91
fa        85
Other     71
so        64
tl        46
tr        28
sw        28
af        26
it        23
ro        22
vi        20
de        20
nl        18
cy        18
hu        17
et        15
fr        14
sl         8
ur         8
pl         7
fi         7
ar         7
ca         6
sv         5
hr         5
da         5
no         5
sq         4
lv         2
cs         2
sk         2
lt         1
ko         1
hi         1
ru         1
pt         1
mk         1
Name: lang, dtype: int64

In [ ]:
df_not_eng

                                                comment hashtag   source lang
3                                    سلامت باشید دوستان  Hazara  YouTube   fa
4                                     درودها قومای عزیز  Hazara  YouTube   fa
5                                     Thanks Huma media  Hazara  YouTube   id
6      اگر هزاره هستن پس طبیعی است که هزاره ثبت می کنید  Hazara  YouTube   fa
10             Allah abad rakhy Pakistan ky hazaras ko.  Hazara  YouTube   id
...                                                 ...     ...      ...  ...
2914       stop hazara genocide in Afghanistan \n           SHG  YouTube   nl
2915  #stophazaragenocide\n#StopPanjshirigenocide\n#...     SHG  YouTube   es
2916            Lanat shuna da dushmanan hazara\n           SHG  YouTube   id
2917  بیرق هزارستان را چرا بلند کردید وقتیکه خود افغ...     SHG  YouTube   fa
2918  Dear Sarwari saib. You are Pakistani Hazara. S...     SHG  YouTube   tr

[807 rows x 4 columns]

On inspection, many of these are in English but are incorrectly labelled. Eg Hasthags are classified as Spanish, and Urdu written in the Latin alphabet is labelled as Indonesian. Detection of non-Latin scripts works well, however.

# Translate comments

## Farsi

In [ ]:
# if lang=fa, get comment
is_farsi = yt['lang'] == 'fa'
df_fa = yt[is_farsi]
print(len(df_fa))

85

In [ ]:
df_fa

                                                comment hashtag   source lang
3                                    سلامت باشید دوستان  Hazara  YouTube   fa
4                                     درودها قومای عزیز  Hazara  YouTube   fa
6      اگر هزاره هستن پس طبیعی است که هزاره ثبت می کنید  Hazara  YouTube   fa
14    ای جانم افتخار میکنم به تک تکی شما خواهرای گلم...  Hazara  YouTube   fa
88    انشاءالله به امید ظهور امام زمان عج و پایان دا...  Hazara  YouTube   fa
...                                                 ...     ...      ...  ...
2858  تشکر ازشما خواهرن و برادران خداوند شماره داشته...     SHG  YouTube   fa
2863  وقتی میفهمیم این مشکلات حل شدنی نیستند بهتر اس...     SHG  YouTube   fa
2879                  هزاره هستین شما یا انسان؟\n           SHG  YouTube   fa
2911  ای چی مسخره بازی ، بیایین یک راه پیدا کنین، دش...     SHG  YouTube   fa
2917  بیرق هزارستان را چرا بلند کردید وقتیکه خود افغ...     SHG  YouTube   fa

[85 rows x 4 columns]

In [ ]:
# export to google drive
df_fa.to_excel("/content/drive/MyDrive/MC/Assessments/A2 & A3/scraped_data/farsi2.xlsx", header=True, index=True)

The dataframe was downloaded as a Google Sheet. The comments were then translated manually using Google Translate  and answers pasted into a new column, 'comment_tr'.

### Import dataframe of comments with Farsi translations

In [ ]:
# upload file with translations in it (new col: 'comment_tr')
farsi_tr = pd.read_excel('/content/drive/MyDrive/MC/Assessments/A2 & A3/scraped_data/farsi2.xlsx', header=0)

In [ ]:
farsi_tr.head()

,ind,comment,hashtag,source,lang,comment_tr
0,3,سلامت باشید دوستان,Hazara,YouTube,fa,Be healthy friends
1,4,درودها قومای عزیز,Hazara,YouTube,fa,"Greetings, dear people"
2,6,اگر هزاره هستن پس طبیعی است که هزاره ثبت می کنید,Hazara,YouTube,fa,"If they are Hazaras, then it is natural that y..."
3,14,ای جانم افتخار میکنم به تک تکی شما خواهرای گلم...,Hazara,YouTube,fa,"My dear, I am proud of each and every one of y..."
4,88,انشاءالله به امید ظهور امام زمان عج و پایان دا...,Hazara,YouTube,fa,"God willing, in the hope of the emergence of I..."

In [ ]:
# set 'ind' column as index 
farsi_tr.set_index('ind', inplace=True)

In [ ]:
farsi_tr.head()

,comment,hashtag,source,lang,comment_tr
ind,,,,,
3,سلامت باشید دوستان,Hazara,YouTube,fa,Be healthy friends
4,درودها قومای عزیز,Hazara,YouTube,fa,"Greetings, dear people"
6,اگر هزاره هستن پس طبیعی است که هزاره ثبت می کنید,Hazara,YouTube,fa,"If they are Hazaras, then it is natural that y..."
14,ای جانم افتخار میکنم به تک تکی شما خواهرای گلم...,Hazara,YouTube,fa,"My dear, I am proud of each and every one of y..."
88,انشاءالله به امید ظهور امام زمان عج و پایان دا...,Hazara,YouTube,fa,"God willing, in the hope of the emergence of I..."

##Urdu (Latin alphabet)

Urdu is detected incorrectly as Indonesian and other languages.

In [ ]:
# filter the df based on multiple conditions to capture bulk of Urdu comments
is_lang_id = yt['lang'] == 'id'
is_lang_so = yt['lang'] == 'so'
is_lang_sw = yt['lang'] == 'sw'
is_lang_sq = yt['lang'] == 'sq'

df_filtered = yt.loc[is_lang_id | is_lang_so | is_lang_sw | is_lang_sq]
df_filtered

                                                comment hashtag   source lang
5                                     Thanks Huma media  Hazara  YouTube   id
10             Allah abad rakhy Pakistan ky hazaras ko.  Hazara  YouTube   id
52                      I m hazara mongol from pakistan  Hazara  YouTube   id
128                    I am Kazakh, supporting Hazaras!  Hazara  YouTube   id
145                                 We went hazaraistan  Hazara  YouTube   sw
...                                                 ...     ...      ...  ...
2791  Mulk az dete khude ma kharab shuda waqte k wat...     SHG  YouTube   id
2801  Mashallah Mashallah Mashallah Mashallah Mashal...     SHG  YouTube   so
2821                           khali qoroot boi\n           SHG  YouTube   so
2833                                   Musallah\n           SHG  YouTube   id
2916            Lanat shuna da dushmanan hazara\n           SHG  YouTube   id

[187 rows x 4 columns]

In [ ]:
# export 
df_filtered.to_excel("/content/drive/MyDrive/MC/Assessments/A2 & A3/scraped_data/df_filtered_tr_urdu.xlsx", header=True, index=True)

Changes made in Google Sheet

### Import dataframe of comments with Urdu translations

In [ ]:
# upload file with translations in it (new col: 'comment_tr')
df_filtered_tr = pd.read_excel('/content/drive/MyDrive/MC/Assessments/A2 & A3/scraped_data/df_filtered_tr_urdu.xlsx', header=0)

In [ ]:
len(df_filtered_tr)

187

In [ ]:
df_filtered_tr.head(20)

,ind,comment,hashtag,source,lang,comment_tr
0,2670,Aghai baqari,SHG,YouTube,id,NO_TRANSLATION
1,2765,#hazara\n,SHG,YouTube,sw,NaN
2,2780,#STOPHAZARAGENOCIDE\n,SHG,YouTube,so,NaN
3,1533,2000 sirf shia hazaramard amrdiye gaye\nNo. On...,SHG,YouTube,so,"2,000 Shia Hazara men alone were martyred\nNin..."
4,523,7 oct 2022 ham tazahorat sartasari dar 91 kish...,SHG,YouTube,id,NO_TRANSLATION
5,1514,Ab ye bhi yahoodi ya raw sazish batado,SHG,YouTube,so,Now tell me that this is also a Jewish conspiracy
6,1038,Abe pakistan me toh koi safe nahi itna bada De...,SHG,YouTube,sq,"Abe, Pakistan is not safe, it is such a bad co..."
7,1494,Afsos hum Karachites ko yh hota hae kae dunya ...,SHG,YouTube,sw,NO_TRANSLATION
8,2648,"ahahahah he died what a noob, hazara aint afghan",SHG,YouTube,so,NaN
9,1383,Aik bht bara paigham ek bht hi sada or asan an...,SHG,YouTube,id,A very bad message explained in a very simple ...
10,868,"Al jalzera be like, ye toh reporting ke bahar hai",SHG,YouTube,id,NO_TRANSLATION
11,700,Alhamdulilah,SHG,YouTube,so,NaN
12,943,Allaah rahem karey onn sob par..\nAur Baaqi Lo...,SHG,YouTube,so,And let the rest of the people also understand...
13,10,Allah abad rakhy Pakistan ky hazaras ko.,Hazara,YouTube,id,May Allahabad bless the Hazaras of Pakistan.
14,1726,Allah allahuh Akbuhah,SHG,YouTube,id,NaN
15,1335,Allah hum sbpe hamare pyare mulk pe rehem kre....,SHG,YouTube,id,May Allah have mercy on all of us and our belo...
16,1089,Allah ka insaaf hi tha bahano... Allah ko Jiha...,SHG,YouTube,so,Allah's justice was the excuse... Allah has to...
17,1488,"Amazing, Koi Mera Channel b dekh lo yar...",SHG,YouTube,id,"Amazing, someone watch my channel"
18,2034,America makes disasters,SHG,YouTube,id,NaN
19,1493,AoA bhai Pakistan Kea sath zulm Hua yea 10 S...,SHG,YouTube,sw,NO_TRANSLATION

In [ ]:
# set 'ind' column as index 
df_filtered_tr.set_index('ind', inplace=True)

In [ ]:
df_filtered_tr.head(20)

,comment,hashtag,source,lang,comment_tr
ind,,,,,
2670,Aghai baqari,SHG,YouTube,id,NO_TRANSLATION
2765,#hazara\n,SHG,YouTube,sw,NaN
2780,#STOPHAZARAGENOCIDE\n,SHG,YouTube,so,NaN
1533,2000 sirf shia hazaramard amrdiye gaye\nNo. On...,SHG,YouTube,so,"2,000 Shia Hazara men alone were martyred\nNin..."
523,7 oct 2022 ham tazahorat sartasari dar 91 kish...,SHG,YouTube,id,NO_TRANSLATION
1514,Ab ye bhi yahoodi ya raw sazish batado,SHG,YouTube,so,Now tell me that this is also a Jewish conspiracy
1038,Abe pakistan me toh koi safe nahi itna bada De...,SHG,YouTube,sq,"Abe, Pakistan is not safe, it is such a bad co..."
1494,Afsos hum Karachites ko yh hota hae kae dunya ...,SHG,YouTube,sw,NO_TRANSLATION
2648,"ahahahah he died what a noob, hazara aint afghan",SHG,YouTube,so,NaN
1383,Aik bht bara paigham ek bht hi sada or asan an...,SHG,YouTube,id,A very bad message explained in a very simple ...
868,"Al jalzera be like, ye toh reporting ke bahar hai",SHG,YouTube,id,NO_TRANSLATION
700,Alhamdulilah,SHG,YouTube,so,NaN
943,Allaah rahem karey onn sob par..\nAur Baaqi Lo...,SHG,YouTube,so,And let the rest of the people also understand...
10,Allah abad rakhy Pakistan ky hazaras ko.,Hazara,YouTube,id,May Allahabad bless the Hazaras of Pakistan.
1726,Allah allahuh Akbuhah,SHG,YouTube,id,NaN
1335,Allah hum sbpe hamare pyare mulk pe rehem kre....,SHG,YouTube,id,May Allah have mercy on all of us and our belo...
1089,Allah ka insaaf hi tha bahano... Allah ko Jiha...,SHG,YouTube,so,Allah's justice was the excuse... Allah has to...
1488,"Amazing, Koi Mera Channel b dekh lo yar...",SHG,YouTube,id,"Amazing, someone watch my channel"
2034,America makes disasters,SHG,YouTube,id,NaN
1493,AoA bhai Pakistan Kea sath zulm Hua yea 10 S...,SHG,YouTube,sw,NO_TRANSLATION

## Merge translations into one dafatrame

In [ ]:
# merge translated dataframes with outer join
cd = pd.merge(farsi_tr, df_filtered_tr, how='outer')
cd.head(110)

,comment,hashtag,source,lang,comment_tr
0,سلامت باشید دوستان,Hazara,YouTube,fa,Be healthy friends
1,درودها قومای عزیز,Hazara,YouTube,fa,"Greetings, dear people"
2,اگر هزاره هستن پس طبیعی است که هزاره ثبت می کنید,Hazara,YouTube,fa,"If they are Hazaras, then it is natural that y..."
3,ای جانم افتخار میکنم به تک تکی شما خواهرای گلم...,Hazara,YouTube,fa,"My dear, I am proud of each and every one of y..."
4,انشاءالله به امید ظهور امام زمان عج و پایان دا...,Hazara,YouTube,fa,"God willing, in the hope of the emergence of I..."
...,...,...,...,...,...
105,Apki baat laik e Tehseen hai Sir but State ki ...,SHG,YouTube,so,NO_TRANSLATION
106,Asalamo Alaikum admin sahab aur team. Khalid A...,SHG,YouTube,id,NO_TRANSLATION
107,Aww zakir lali khaw to amda \n,SHG,YouTube,sw,NO_TRANSLATION
108,"baat poori trhan se sahi nahi hai , aik fiqah ...",SHG,YouTube,so,NO_TRANSLATION
109,Bahut achha kiya Muslim logo ne yehi hona chah...,SHG,YouTube,id,NO_TRANSLATION

In [ ]:
len(cd)

272

In [ ]:
cd

,comment,hashtag,source,lang,comment_tr
0,سلامت باشید دوستان,Hazara,YouTube,fa,Be healthy friends
1,درودها قومای عزیز,Hazara,YouTube,fa,"Greetings, dear people"
2,اگر هزاره هستن پس طبیعی است که هزاره ثبت می کنید,Hazara,YouTube,fa,"If they are Hazaras, then it is natural that y..."
3,ای جانم افتخار میکنم به تک تکی شما خواهرای گلم...,Hazara,YouTube,fa,"My dear, I am proud of each and every one of y..."
4,انشاءالله به امید ظهور امام زمان عج و پایان دا...,Hazara,YouTube,fa,"God willing, in the hope of the emergence of I..."
...,...,...,...,...,...
267,Ye Hindi bolte hai aur ye behsarm muslaman sun...,SHG,YouTube,id,They speak Hindi and these Muslim Sunnis are s...
268,Ye khuda ki wazah se hi to ye mar rahe hai...,SHG,YouTube,sw,It's clear from God that it's dying...
269,Ye koi shia sunni ki larai nhi horahi ye kch o...,SHG,YouTube,id,"This is not a Shia-Sunni fight, it is a Kachwa..."
270,Yi sab pakistan ki dushman ki sazish hi .,SHG,YouTube,id,This is all the conspiracy of Pakistan's enemy.
271,zulm k khilaaaf bolna chahiye.... well said kh...,SHG,YouTube,so,We should speak against oppression.... For Sye...

In [ ]:
# set 'ind' column as index 
yt.set_index('ind', inplace=True)

In [ ]:
yt.head()

                                             comment hashtag   source lang
0  Another amazing video! So wonderful to see all...  Hazara  YouTube   en
1  Beautiful people, love from Iran to my lovely ...  Hazara  YouTube   en
2                             Love my nation Hazara   Hazara  YouTube   en
3                                 سلامت باشید دوستان  Hazara  YouTube   fa
4                                  درودها قومای عزیز  Hazara  YouTube   fa

In [ ]:
len(yt)

2919

In [ ]:
len(cd)

272

In [ ]:
new = pd.merge(yt, cd, how='outer')

In [ ]:
len(new)

2942

In [ ]:
new.head()

,comment,hashtag,source,lang,comment_tr
0,Another amazing video! So wonderful to see all...,Hazara,YouTube,en,NaN
1,"Beautiful people, love from Iran to my lovely ...",Hazara,YouTube,en,NaN
2,Love my nation Hazara,Hazara,YouTube,en,NaN
3,سلامت باشید دوستان,Hazara,YouTube,fa,Be healthy friends
4,درودها قومای عزیز,Hazara,YouTube,fa,"Greetings, dear people"

In [ ]:
# export a copy
new.to_excel("new.xlsx", header=True, index=True)

### Update the comments with translations of Farsi and Urdu

In [ ]:
# Iterate over rows and replace values in 'comment' column if there is a translated  ocomment 
for index, row in new.iterrows():
    if not pd.isna(row['comment_tr']):
        new.loc[index, 'comment'] = row['comment_tr']

In [ ]:
new

,comment,hashtag,source,lang,comment_tr
0,Another amazing video! So wonderful to see all...,Hazara,YouTube,en,NaN
1,"Beautiful people, love from Iran to my lovely ...",Hazara,YouTube,en,NaN
2,Love my nation Hazara,Hazara,YouTube,en,NaN
3,Be healthy friends,Hazara,YouTube,fa,Be healthy friends
4,"Greetings, dear people",Hazara,YouTube,fa,"Greetings, dear people"
...,...,...,...,...,...
2937,#stophazaragenocide\n#StopPanjshirigenocide\n#...,SHG,YouTube,es,NaN
2938,Curse the enemies of Hazara\n,SHG,YouTube,id,Curse the enemies of Hazara\n
2939,بیرق هزارستان را چرا بلند کردید وقتیکه خود افغ...,SHG,YouTube,fa,NaN
2940,Dear Sarwari saib. You are Pakistani Hazara. S...,SHG,YouTube,tr,NaN
2941,Why did you raise the flag of Hazaristan when ...,NaN,NaN,NaN,Why did you raise the flag of Hazaristan when ...

## Inspect and translate other languages within the dataframe

In this section, we make changes within the dataframe, without exporting and importing changes made in a spreadsheet

### German

In [ ]:
# update german
# if lang=, get row
is_german = new['lang'] == 'de'
df_ge = new[is_german]
df_ge

,comment,hashtag,source,lang,comment_tr
638,"GREAT JOB LADIES, KEEP IT UP.",SHG,YouTube,de,NaN
788,PAKISTAN ZINDABAD 🇵🇰️,SHG,YouTube,de,NaN
823,Chinese Kung Fu.,SHG,YouTube,de,NaN
873,FREE UIGHAR MUSLIMS,SHG,YouTube,de,NaN
1036,Madness !!!,SHG,YouTube,de,NaN
1195,All were Buddhist.,SHG,YouTube,de,NaN
1220,Liberate Balochistan Sindh PoK frm TERRORISTAAN,SHG,YouTube,de,NaN
1239,Hehehehehehe ISLAM on rise,SHG,YouTube,de,NaN
1245,"MAY ALLHA NAQS NABUD KARDE PAKISTANIES KO ,LAN...",SHG,YouTube,de,NaN
1264,No life in Afghanistan under Taliban,SHG,YouTube,de,NaN
1304,Biden's Fault,SHG,YouTube,de,NaN
1324,VERY WELL SAID. WE MUST BE ONE AGAINST OUR ENE...,SHG,YouTube,de,NaN
1356,Just Speechless,SHG,YouTube,de,NaN
1426,Well said sir \nBest human being sir,SHG,YouTube,de,NaN
1895,:D :D :D,SHG,YouTube,de,NaN
1950,WHATS WRONG EOTHTHRSE PEOPLE'S,SHG,YouTube,de,NaN
2170,STOP MAKING IT LOOK SO BAD,SHG,YouTube,de,NaN
2210,Sehr Informationsreiches Video über Hazara \n#...,SHG,YouTube,de,NaN
2621,LONG LIVE SADDAM\n,SHG,YouTube,de,NaN
2910,Diese Menschen sind nicht so gut \n,SHG,YouTube,de,NaN

In [ ]:
# add translation from German
new['comment_tr'].loc[[2210]] = 'very informative video about Hazaras #StopHazaraGenocide'
new['comment_tr'].loc[[2910]] = 'These people are not so good'

# replace comments with translation for specified indices
# specify the indices to replace values for
indices_to_replace = [2210, 2910]

# loop over the indices and replace the values in 'comment' column with 'comment_tr'
for index in indices_to_replace:
    if not pd.isna(new.loc[index, 'comment_tr']):
        new.loc[index, 'comment'] = new.loc[index, 'comment_tr']

# check
new.loc[[2210, 2910]]

,comment,hashtag,source,lang,comment_tr
2210,very informative video about Hazaras #StopHaza...,SHG,YouTube,de,very informative video about Hazaras #StopHaza...
2910,These people are not so good,SHG,YouTube,de,These people are not so good

### Urdu (script)

In [ ]:
# Urdu
is_ur = new['lang'] == 'ur'
df_ur = new[is_ur]
df_ur

,comment,hashtag,source,lang,comment_tr
673,ماشاء اللہ ماشاء اللہ بہت خوب اللہ پاک آپ کو ک...,SHG,YouTube,ur,NaN
1327,میں سنی ہوں میں اپنی ہزارہ کمیونٹی کے دکھ میں ...,SHG,YouTube,ur,NaN
1487,بہترین نصیحت۔,SHG,YouTube,ur,NaN
1488,انسانی حقوق کا انکارسیدھا سیدھا انسانیت پر اعت...,SHG,YouTube,ur,NaN
1510,پاکستان زندہ باد,SHG,YouTube,ur,NaN
1574,اپ سے میں پوچھتا ہو اپ گھر سے یا کے ٹاون سے 20...,SHG,YouTube,ur,NaN
1579,سیکیورٹی دینا کس کا کام ہے؟ وزیراعظم ارتغل کے ...,SHG,YouTube,ur,NaN
1587,تمہارا کوئی مرتا نہ تو پھر تقریر کرتے۔,SHG,YouTube,ur,NaN

In [ ]:
# add translation for Urdu
new['comment_tr'].loc[[673]] = 'Masha Allah Masha Allah very good may Allah bless you with success Amen Prayer request'
new['comment_tr'].loc[[1327]] = 'I am Sunni I am an equal sharer in the suffering of my Hazara community ️ from punjab'
new['comment_tr'].loc[[1487]] = 'Excellent advice.'
new['comment_tr'].loc[[1488]] = 'The denial of human rights is a direct objection to humanity.'
new['comment_tr'].loc[[1510]] = 'Long live Pakistan'
new['comment_tr'].loc[[1574]] = 'I am asking you, if you kill people from your home or from your town for 20 years continuously, then you will not do anything. Five dead bodies have come out of your house by the grace of God....we are talking about the body... Those people are sitting right...'
new['comment_tr'].loc[[1579]] = 'Whose job is to provide security? The Prime Minister is not getting out of the spell of Ertuğl'
new['comment_tr'].loc[[1587]] = 'None of you would have died, then you would have given a speech.'

# replace comments with translation for specified indices
# specify the indices to replace values for
indices_to_replace = [673,1327,1487,1488,1510,1574,1579,1587]

# loop over the indices and replace the values in 'comment' column with 'comment_tr'
for index in indices_to_replace:
    if not pd.isna(new.loc[index, 'comment_tr']):
        new.loc[index, 'comment'] = new.loc[index, 'comment_tr']

### French

In [ ]:
# if lang=, get comment
is_french = new['lang'] == 'fr'
df_fr = new[is_french]
df_fr

,comment,hashtag,source,lang,comment_tr
640,Beautiful courageous girls️️️,SHG,YouTube,fr,NaN
1286,I support you,SHG,YouTube,fr,NaN
1367,Beautiful message!,SHG,YouTube,fr,NaN
1377,"️, beautiful Message.",SHG,YouTube,fr,NaN
1392,love you sir you are great,SHG,YouTube,fr,NaN
1467,Such description,SHG,YouTube,fr,NaN
1709,Praise be,SHG,YouTube,fr,NaN
1841,English conquerors rest!!!!,SHG,YouTube,fr,NaN
1971,"Not true ,,,",SHG,YouTube,fr,NaN
2119,Distractions distractions distractions,SHG,YouTube,fr,NaN
2185,Lair,SHG,YouTube,fr,NaN
2424,"Brave Afghan ladies, may you be victorious!!\n...",SHG,YouTube,fr,NaN
2521,"Brave Afghan ladies, may you be victorious!!\n...",SHG,YouTube,fr,NaN
2610,Revolution \n,SHG,YouTube,fr,NaN

None of these comments was in French so we will do nothing

### Arabic

In [ ]:
# Arabic
# if lang=, get comment
is_arab = new['lang'] == 'ar'
df_ar = new[is_arab]
df_ar

                                  comment hashtag   source lang comment_tr
380                     حفظ الله شيعة علي  Hazara  YouTube   ar        NaN
2313                                 عالی     SHG  YouTube   ar        NaN
2756                                    ،     SHG  YouTube   ar        NaN
2787  اللهم صلي على محمد وال محمد\n           SHG  YouTube   ar        NaN
2829        موفق باشید ان‌شاءالله\n           SHG  YouTube   ar        NaN
2875   موفق باشید عزیزان ملبورن .\n           SHG  YouTube   ar        NaN
2914                         متحد\n           SHG  YouTube   ar        NaN

### Hindi (script)

In [ ]:
# Hindi
is_hi = new['lang'] == 'hi'
df_hi = new[is_hi]
df_hi

,comment,hashtag,source,lang,comment_tr
924,टिड्डी दल \n1. पसंद रंग : हरा\n 2. रहन सहन : झ...,SHG,YouTube,hi,NaN

In [ ]:
# add translation directly to df for Arabic & Hindi
new['comment_tr'].loc[[380]] = 'May God protect Shia Ali'
new['comment_tr'].loc[[2313]] = 'High'
new['comment_tr'].loc[[2756]] = 'NO_TRANSLATION'
new['comment_tr'].loc[[2787]] = 'The blessings of God to Muhammad and his family'
new['comment_tr'].loc[[2829]] = 'Good luck, God willing'
new['comment_tr'].loc[[2875]] = 'Good luck dear Melbourne'
new['comment_tr'].loc[[2914]] = 'united'
new['comment_tr'].loc[[924]] = 'Locust Party 1. Favorite Colour: Green 2. Living Tolerance: They like to live in herds. 3. Identification: uncontrolled reproduction'

# specify the indices to replace values for
indices_to_replace = [380, 2313, 2756, 2787, 2829, 2875, 2914, 924]

# loop over the indices and replace the values in 'comment' column with 'comment_tr'
for index in indices_to_replace:
    if not pd.isna(new.loc[index, 'comment_tr']):
        new.loc[index, 'comment'] = new.loc[index, 'comment_tr']

In [ ]:
# replace another Farsi comment
new['comment_tr'].loc[[2939]] = 'Bairaq Hazarastan is a timely and well-known Afghan community of martyrs outside of Duma, in what it has, with a number of 40 people in Herat, a number of 30 people in a mosque in Sarkotl Khirkhana, a number of 15 people in a mosque of Wazir Akbar Khan, another martyr Objection can be made by nationality, objection is not made, but the descendants of Afghans are subject to item, not a special nation.'

index_to_replace = [2939]
for index in index_to_replace:
    if not pd.isna(new.loc[index, 'comment_tr']):
        new.loc[index, 'comment'] = new.loc[index, 'comment_tr']

### Remove rows with lang = 'Other' 

These  have nonsensical information or are blank

In [ ]:
# remove Other
# subset Other rows
is_other = new['lang'] == 'Other'
df_null = new[is_other]
new = new.drop(df_null.index)
len(new)

2871

### No translation possible

In [ ]:
# remove rows with NO_TRANSLATION
# subset rows then drop
is_notrans = new['comment_tr'] == 'NO_TRANSLATION'
df_notrans = new[is_notrans]
new = new.drop(df_notrans.index)
len(new)

2821

Change the values in comments_tr column to 'y' or 'n'

In [ ]:
import numpy as np

# Apply the lambda function to replace values in the 'comment_tr' column
new['comment_tr'] = new['comment_tr'].apply(lambda x: 'yes' if not pd.isna(x) else 'no')

In [ ]:
new.head()

,comment,hashtag,source,lang,comment_tr
0,Another amazing video! So wonderful to see all...,Hazara,YouTube,en,no
1,"Beautiful people, love from Iran to my lovely ...",Hazara,YouTube,en,no
2,Love my nation Hazara,Hazara,YouTube,en,no
3,Be healthy friends,Hazara,YouTube,fa,yes
4,"Greetings, dear people",Hazara,YouTube,fa,yes

## Export

In [ ]:
# export to temporary location
new.to_excel("new_final.xlsx", header=True, index=True)

In [ ]:
# export to drive
new.to_excel("/content/drive/MyDrive/MC/Assessments/A2 & A3/scraped_data/new_final.xlsx", header=True, index=True)

In [ ]:
!python --version

Python 3.9.16